import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Link from "next/link";
import AuthProvider from "./context/AuthProvider";
import CartBtn from "./components/button/cartBtn";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ 
    children: React.ReactNode; 
  }>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="container">
        <AuthProvider>
            <NavBar />
              <div className="min-h-screen w-screen md:flex max-sm:max-w-[425px]">
                <Sidebar />
                <div className="mx-24 rounded-lg md:flex-1 bg-sky-50 max-sm:mx-3 max-sm:text-xs">
                  {children}
                </div>
              </div>
          </AuthProvider>
        </section>
          
          
      </body>
    </html>
  );
}
