import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Link from "next/link";
import AuthProvider from "./context/AuthProvider";
import CartBtn from "./components/button/cartBtn";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ 
    children: React.ReactNode; 
  }>) {

  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
            <NavBar />
              <div className="min-h-screen w-full flex">
                <Sidebar />
                <div className="mx-24 rounded-lg min-w-[450px] flex-1 bg-sky-50">
                  {children}
                </div>
              </div>
          </AuthProvider>
          
      </body>
    </html>
  );
}
